version: "3.9"

services:
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend/:/app/frontend
  #   ports:
  #     - 5173:5173
  #     - 80:4173
  #   depends_on:
  #     - backend
  #   # network_mode: "host"

  # backend:
  #   build: ./backend
  #   volumes:
  #     - ./backend:/app/backend
  #   ports:
  #     - 8000:3000
  #   depends_on:
  #     - postgres
  #     - mongo

  postgres:
    image: postgis/postgis
    ports:
      - ${POSTGRES_EXTERNAL_PORT:-5432}:5432
    environment:
      POSTGRES_DB: psql
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: yesno
    volumes:
      - .pg_data:/var/lib/postgresql
    # restart: always

  # mongo:
  #   image: mongo:latest
  #   # restart: always
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME:baskim
  #     - MONGO_INITDB_ROOT_PASSWORD:yesno
  #   volumes:
  #     - .mongo_data:/data/db
  #   # ports:
  #   #   - 27017:27017

volumes:
  postgres_data:
  # mongo_data:
